# Generated by Django 4.0.1 on 2022-01-31 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_books_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='books',
            managers=[
            ],
        ),
    ]
